language: python
before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - sudo apt-get install python3-pip
install:
  - pip3 install -r requirements.txt
script:
  - python3 manage.py test
